# Generated by Django 3.0.5 on 2020-06-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('place', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
