# Generated by Django 3.0.5 on 2020-06-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinations',
            name='time',
        ),
        migrations.AddField(
            model_name='destinations',
            name='date',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='destinations',
            name='personDescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='personName',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='personphoto',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
